/* eslint-disable prettier/prettier */
export const AuthConstants = {
  SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
};
