/* eslint-disable prettier/prettier */
export const CartConstants = {
    CART_LUMSUM_REQUEST: ' CART_LUMSUM_REQUEST',
    CART_LUMSUM_SUCCESS: ' CART_LUMSUM_SUCCESS',
    CART_LUMSUM_FAILURE: ' CART_LUMSUM_FAILURE',

    CART_LUMSUM_REQUEST: ' CART_LUMSUM_REQUEST',
    CART_LUMSUM_SUCCESS: ' CART_LUMSUM_SUCCESS',
    CART_LUMSUM_FAILURE: ' CART_LUMSUM_FAILURE',
  };
  