/* eslint-disable prettier/prettier */
export const ExploreConstants = {
    INVESTMENT_DETAIL_REQUEST: 'INVESTMENT_DETAIL_REQUEST',
    INVESTMENT_DETAIL_SUCCESS: 'INVESTMENT_DETAIL_SUCCESS',
    INVESTMENT_DETAIL_FAILURE: 'INVESTMENT_DETAIL_FAILURE',

  };
  