/* eslint-disable prettier/prettier */
export const MutualFundsConstants = {
    MY_MUTUAL_FUNDS_REQUEST: 'MY_MUTUAL_FUNDS_REQUEST',
    MY_MUTUAL_FUNDS_SUCCESS: 'MY_MUTUAL_FUNDS_SUCCESS',
    MY_MUTUAL_FUNDS_FAILURE: 'MY_MUTUAL_FUNDS_FAILURE',
    
    XIR_REQUEST: 'XIR_REQUEST',
    XIR_SUCCESS: 'XIR_SUCCESS',
    XIR_FAILURE: 'XIR_FAILURE',

    CONSOLIDATED_REQUEST: 'CONSOLIDATED_REQUEST',
    CONSOLIDATED_SUCCESS: 'CONSOLIDATED_SUCCESS',
    CONSOLIDATED_FAILURE: 'CONSOLIDATED_FAILURE',

    ALL_MUTUAL_FUNDS_REQUEST: 'ALL_MUTUAL_FUNDS_REQUEST',
    ALL_MUTUAL_FUNDS_SUCCESS: 'ALL_MUTUAL_FUNDS_SUCCESS',
    ALL_MUTUAL_FUNDS_FAILURE: 'ALL_MUTUAL_FUNDS_FAILURE',

    FUND_SCREENER_REQUEST: 'FUND_SCREENER_REQUEST',
    FUND_SCREENER_SUCCESS: 'FUND_SCREENER_SUCCESS',
    FUND_SCREENER_FAILURE: 'FUND_SCREENER_FAILURE',

    NFO_REQUEST: 'NFO_REQUEST',
    NFO_SUCCESS: 'NFO_SUCCESS',
    NFO_FAILURE: 'NFO_FAILURE',

  };
  