/* eslint-disable prettier/prettier */
export const SessionConstant = {
    SESSION_REQUEST: 'SESSION_REQUEST',
    SESSION_SUCCESS: 'SESSION_SUCCESS',
    SESSION_FAILURE: 'SESSION_FAILURE',

    SET_SESSION_REQUEST: 'SET_SESSION_REQUEST',
    SET_SESSION_SUCCESS: 'SET_SESSION_SUCCESS',
    SET_SESSION_FAILURE: 'SET_SESSION_FAILURE',
  };
  